mappings:
  AnalyticsTransactionReversal: Sunnysideup\EcommerceGoogleAnalytics\AnalyticsTransactionReversal
  CheckoutPageDataExtension: Sunnysideup\EcommerceGoogleAnalytics\CheckoutPageDataExtension
  CheckoutPageExtensionController: Sunnysideup\EcommerceGoogleAnalytics\CheckoutPageExtensionController
