---
Name: ecommerce-google-analytics
---
Order:
  extensions:
    - AnalyticsTransactionReversal

CheckoutPage:
  extensions:
    - CheckoutPageDataExtension

CheckoutPageController:
  extensions:
    - CheckoutPageExtensionController

CheckoutPageExtensionController:
  include_product_items: true