---
Name: ecommerce-google-analytics
---
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceGoogleAnalytics\AnalyticsTransactionReversal
Sunnysideup\Ecommerce\Pages\CheckoutPage:
  extensions:
    - Sunnysideup\EcommerceGoogleAnalytics\CheckoutPageDataExtension
Sunnysideup\Ecommerce\Pages\CheckoutPageController:
  extensions:
    - Sunnysideup\EcommerceGoogleAnalytics\CheckoutPageExtensionController
Sunnysideup\EcommerceGoogleAnalytics\CheckoutPageExtensionController:
  include_product_items: true
